#!/bin/bash
echo "WEBSOCKET shell file running.."
pkill -f "/usr/local/bin/nodemon start SOC.js"
PORT=3003
PID=$(lsof -i:$PORT | awk 'NR==2{print $2}');
if [ ! -z "$PID" ]; then
  kill -9 $PID
  echo "$PID KILLED"
fi
nodemon start SOC.js